name: CI

on: [push, pull_request]
jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Psalm
        uses: docker://vimeo/psalm-github-actions
        with:
          args: --shepherd
